// Supply only a migrated disposable database.
if(process.env.TEST_DATABASE_URL)process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;
import {randomUUID} from 'crypto';
import {Prisma} from '@prisma/client';
import prisma from '../../prisma/client';
import {PartyNoteService} from './party-note.service';
import {PartyAccountService,availablePartyCredit} from './party-account.service';
import {ReceiptService} from './receipt.service';
import {PartyReportService} from './party-report.service';
import {partyReportQuery} from './party-report.validation';
import {TallyService} from './tally.service';
import {noteRegisterQuery} from './party-note.validation';
const integration=process.env.TEST_DATABASE_URL?describe:describe.skip;
integration('Debit and credit notes in PostgreSQL',()=>{
 afterAll(async()=>{await prisma.$disconnect();});
 it('posts bounced receipt debits, spends credit notes once, preserves history and enforces cancellation/posting guards',async()=>{
  const rollback=new Error('ROLLBACK_NOTE_FIXTURES'),original=prisma.$transaction.bind(prisma);
  await expect(original(async tx=>{
   const suffix=randomUUID(),branch=await tx.branch.create({data:{name:'notes-'+suffix}});
   const role=await tx.role.upsert({where:{name:'Admin'},create:{name:'Admin'},update:{}});
   const actor=await tx.user.create({data:{email:suffix+'@example.test',firstName:'Test',lastName:'Admin',passwordHash:'not-a-login',roleId:role.id,branchId:branch.id}});
   const partyLedger=await tx.tallyLedger.create({data:{code:'party-'+suffix,name:'A & B <Party>',active:true}});
   const account=await tx.tallyLedger.create({data:{code:'account-'+suffix,name:'Correction & Charges',active:true}});
   const customer=await tx.customer.create({data:{code:'note-'+suffix,firstName:'Note',lastName:'Party',branchId:branch.id,house:'12',street:'Test street',city:'Lagos',state:'Lagos',tallyLedgerId:partyLedger.id}});
   const date=new Date(Date.now()-3*86400000).toISOString().slice(0,10),asOn=new Date().toISOString().slice(0,10);
   const spy=jest.spyOn(prisma,'$transaction').mockImplementation(((callback:(client:Prisma.TransactionClient)=>Promise<unknown>)=>callback(tx)) as typeof prisma.$transaction);
   const noteRead=jest.spyOn(prisma.partyNote,'findUnique').mockImplementation(tx.partyNote.findUnique.bind(tx.partyNote) as typeof prisma.partyNote.findUnique);
   try{
    const notes=new PartyNoteService(),adjustments=new PartyAccountService(),reports=new PartyReportService(),tally=new TallyService();
    const invoice=await tx.invoice.create({data:{customerId:customer.id,invoiceNumber:'note-bill-'+suffix,issuedDate:new Date(Date.now()-5*86400000),subtotal:100,tax:0,total:100,outstandingAmount:100,status:'Unpaid'}});
    const receipt=await new ReceiptService().createReceipt({customerId:customer.id,branchId:branch.id,issuedById:actor.id,mode:'CASH',category:'SERVICE_PARTS',amount:100,issuedAt:new Date(Date.now()-4*86400000).toISOString(),allocations:[{invoiceId:invoice.id,amount:100}],idempotencyKey:randomUUID()});
    await tx.receipt.update({where:{id:receipt.id},data:{tallyPostedAt:new Date()}});
    const debitInput={customerId:customer.id,branchId:branch.id,date,narration:'Bounced cheque',amount:60,idempotencyKey:randomUUID(),direction:'DEBIT' as const,type:'RECEIPT' as const,receiptLines:[{receiptId:receipt.id,amount:60}]};
    const debit=await notes.create(debitInput,actor.id);expect((await notes.create(debitInput,actor.id)).id).toBe(debit.id);
    await expect(notes.create({...debitInput,amount:61,receiptLines:[{receiptId:receipt.id,amount:61}]},actor.id)).rejects.toThrow('request key');
    await expect(notes.create({...debitInput,idempotencyKey:randomUUID(),amount:101,receiptLines:[{receiptId:receipt.id,amount:101}]},actor.id)).rejects.toThrow('cannot exceed');
    expect(debit.number).toMatch(/^\d{10}$/);expect(debit.remainingAmount.toNumber()).toBe(60);expect(debit.receiptLines[0].receiptNumber).toBe(receipt.receiptNumber);expect(debit.partyAddress).toContain('Test street');
    expect((await tx.invoice.findUniqueOrThrow({where:{id:invoice.id}})).outstandingAmount).toBe(0);
    const report=await reports.report(partyReportQuery.parse({kind:'outstanding',customerId:customer.id,branchId:branch.id,asOn}));expect(report.rows[0].net).toBe(60);
    const age=await reports.report(partyReportQuery.parse({kind:'age',customerId:customer.id,branchId:branch.id,asOn}));expect(age.rows[0].bucket0).toBe(60);
    const credit=await notes.create({customerId:customer.id,branchId:branch.id,date,narration:'Goodwill',amount:20,idempotencyKey:randomUUID(),direction:'CREDIT',type:'AMOUNT',accountLines:[{ledgerId:account.id,narration:'Credit split',amount:20}]},actor.id);
    expect(await availablePartyCredit(tx,customer.id)).toBe(20);
    const nextInvoice=await tx.invoice.create({data:{customerId:customer.id,invoiceNumber:'credit-bill-'+suffix,issuedDate:new Date(Date.now()-2*86400000),subtotal:50,tax:0,total:50,outstandingAmount:50,status:'Unpaid'}});
    const batch=await adjustments.createAdjustment({customerId:customer.id,branchId:branch.id,date:new Date().toISOString(),source:'ADVANCE_ADJUSTMENT',idempotencyKey:randomUUID(),debits:[{id:nextInvoice.id,kind:'INVOICE',amount:20}],credits:[{id:credit.id,kind:'NOTE',amount:20}]},actor.id);
    expect((await tx.invoice.findUniqueOrThrow({where:{id:nextInvoice.id}})).outstandingAmount).toBe(30);expect(await availablePartyCredit(tx,customer.id)).toBe(0);
    await expect(notes.cancel(credit.id,'Correct',actor.id)).rejects.toThrow('Adjusted');
    await adjustments.reverse(batch.id,'Correction',actor.id);
    const before=await reports.report(partyReportQuery.parse({kind:'outstanding',customerId:customer.id,branchId:branch.id,asOn:date}));
    await notes.cancel(credit.id,'No longer required',actor.id);
    const past=await reports.report(partyReportQuery.parse({kind:'outstanding',customerId:customer.id,branchId:branch.id,asOn:date}));expect(past.rows[0].net).toBe(before.rows[0].net);
    expect(await availablePartyCredit(tx,customer.id)).toBe(0);
    const filters=noteRegisterQuery.parse({direction:'DEBIT',from:date,to:asOn,branchId:branch.id,pageSize:1});
    const register=await notes.register(filters);expect(register.meta.total).toBe(1);expect(register.totals.amount.toNumber()).toBe(60);
    const streamed:string[]=[];await notes.stream(filters,async rows=>{streamed.push(...rows.map(n=>n.id));});expect(streamed).toEqual([debit.id]);
    await tx.tallyAccountMapping.create({data:{documentType:'DEBIT_NOTE',accountType:'RECEIPT',tallyLedgerCode:account.code,tallyLedgerName:account.name}});
    const debitExport=await tally.exportBatch({documents:[{type:'DEBIT_NOTE',id:debit.id}],postedById:actor.id});
    expect(debitExport.exported).toHaveLength(1);expect(debitExport.xml).toContain('VCHTYPE="Debit Note"');expect(debitExport.xml).toContain('<AMOUNT>-60.00</AMOUNT>');
    await tally.confirmBatch({batchId:debitExport.batchId,postedById:actor.id,documents:[{type:'DEBIT_NOTE',id:debit.id,voucherNumber:'DN-TEST'}]});
    await expect(notes.cancel(debit.id,'Correction',actor.id)).rejects.toThrow('Tally-posted');
    const postedCredit=await notes.create({customerId:customer.id,branchId:branch.id,date,narration:'Credit voucher',amount:0.3,idempotencyKey:randomUUID(),direction:'CREDIT',type:'AMOUNT',accountLines:[{ledgerId:account.id,narration:'A',amount:0.1},{ledgerId:account.id,narration:'B',amount:0.2}]},actor.id);
    const creditExport=await tally.exportBatch({documents:[{type:'CREDIT_NOTE',id:postedCredit.id}],postedById:actor.id});
    expect(creditExport.exported).toHaveLength(1);expect(creditExport.xml).toContain('VCHTYPE="Credit Note"');expect(creditExport.xml).toContain('<AMOUNT>0.30</AMOUNT>');
    await tally.confirmBatch({batchId:creditExport.batchId,postedById:actor.id,documents:[{type:'CREDIT_NOTE',id:postedCredit.id,voucherNumber:'CN-TEST'}]});
    const postedBatch=await adjustments.createAdjustment({customerId:customer.id,branchId:branch.id,date:new Date().toISOString(),source:'ADVANCE_ADJUSTMENT',idempotencyKey:randomUUID(),debits:[{id:nextInvoice.id,kind:'INVOICE',amount:0.3}],credits:[{id:postedCredit.id,kind:'NOTE',amount:0.3}]},actor.id);
    await expect(adjustments.reverse(postedBatch.id,'Correction',actor.id)).rejects.toThrow('Tally');
    await expect(notes.cancel(postedCredit.id,'Correction',actor.id)).rejects.toThrow('Tally-posted');
    const disposable=await notes.create({...debitInput,type:'AMOUNT',receiptLines:[],amount:1,idempotencyKey:randomUUID()},actor.id);
    const pending=await tally.exportBatch({documents:[{type:'DEBIT_NOTE',id:disposable.id}],postedById:actor.id});expect(pending.skipped[0].reason).toContain('Missing Tally account mapping');
    await tx.tallyAccountMapping.create({data:{documentType:'DEBIT_NOTE',accountType:'AMOUNT',tallyLedgerCode:account.code,tallyLedgerName:account.name}});
    const exp=await tally.exportBatch({documents:[{type:'DEBIT_NOTE',id:disposable.id}],postedById:actor.id});expect(exp.exported).toHaveLength(1);
    await notes.cancel(disposable.id,'Not imported',actor.id);expect((await tx.tallyPostingLog.findUniqueOrThrow({where:{documentType_documentId:{documentType:'DEBIT_NOTE',documentId:disposable.id}}})).status).toBe('INVALIDATED');
    await expect(tally.confirmBatch({batchId:exp.batchId,postedById:actor.id,documents:[{type:'DEBIT_NOTE',id:disposable.id,voucherNumber:'INVALID'}]})).rejects.toThrow('not exported');
    const ledger=await reports.report(partyReportQuery.parse({kind:'ledger',customerId:customer.id,branchId:branch.id,from:date,to:asOn,pageSize:100}));const current=await reports.report(partyReportQuery.parse({kind:'outstanding',customerId:customer.id,branchId:branch.id,asOn}));expect(ledger.rows.at(-1)?.closing).toBe(current.rows[0].net);
    expect(await tx.auditLog.count({where:{userId:actor.id,action:'PARTY_NOTE_TALLY_POSTED'}})).toBe(2);
   }finally{noteRead.mockRestore();spy.mockRestore();}
   throw rollback;
  },{timeout:60000})).rejects.toBe(rollback);
 },70000);
});
