import express from 'express';
import { Server } from 'http';
import { AddressInfo } from 'net';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { gzipSync } from 'zlib';
import { randomUUID } from 'crypto';
import { parseCatalog, normalizeCatalogName, catalogAliases } from './catalog-source';
jest.mock('../../middleware/authMiddleware', () => ({ authMiddleware: (_req: unknown, _res: unknown, next: () => void) => next() }));
jest.mock('../../prisma/client', () => ({ __esModule: true, default: { vehicleCatalogModel: { findMany: jest.fn(), findUnique: jest.fn() } } }));
import prisma from '../../prisma/client';
import router from './vehicle-catalog.routes';
const findMany = prisma.vehicleCatalogModel.findMany as jest.Mock;
const findUnique = prisma.vehicleCatalogModel.findUnique as jest.Mock;
let server: Server;
let base: string;
beforeAll(async () => {
  const app = express(); app.use('/api/vehicle-catalog', router);
  app.use((error: { statusCode?: number; message: string }, _req: express.Request, res: express.Response, _next: express.NextFunction) => { res.status(error.statusCode ?? 500).json({ message: error.message }); });
  server = await new Promise<Server>(resolveServer => { const listener = app.listen(0, '127.0.0.1', () => resolveServer(listener)); });
  base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api/vehicle-catalog`;
});
afterAll(() => new Promise<void>((resolveClose, reject) => server.close(error => error ? reject(error) : resolveClose())));
it('returns a small model list without specs, caches it and supports ETag revalidation', async () => {
  const source = parseCatalog(JSON.parse(readFileSync(resolve(__dirname, '../../../data/kia.json'), 'utf8'))).data;
  findMany.mockResolvedValue(source.makes.flatMap(make => make.models.map(model => ({ id: randomUUID(), name: model.name, searchName: normalizeCatalogName(model.name), aliases: catalogAliases(model.name), yearStart: model.yearStart, yearEnd: model.yearEnd, make: { name: make.name } }))));
  const response = await fetch(`${base}/models`);
  expect(response.status).toBe(200);
  expect(response.headers.get('cache-control')).toBe('public, max-age=86400');
  const body = await response.text();
  expect(JSON.parse(body).data).toHaveLength(47);
  expect(body).not.toContain('specs');
  expect(Buffer.byteLength(body)).toBeLessThan(12_000);
  expect(gzipSync(body).length).toBeLessThan(3_500);
  expect(findMany.mock.calls[0][0].select).not.toHaveProperty('generations');
  const cached = await fetch(`${base}/models`, { headers: { 'If-None-Match': response.headers.get('etag')!, 'Cache-Control': 'max-age=0' } });
  expect(cached.status).toBe(304);
  expect(findMany).toHaveBeenCalledTimes(1);
});
it('returns compact options without selecting specs and returns 404 for missing models', async () => {
  const id = randomUUID();
  findUnique.mockResolvedValueOnce({ id, generations: [{ id: randomUUID(), name: 'RIO', yearStart: 2020, yearEnd: null, engines: [{ id: randomUUID(), label: '1.4L', fuelType: 'Gasoline', powerHp: null, transmission: null, drivetrain: null }] }] });
  const response = await fetch(`${base}/models/${id}/options`);
  expect(response.status).toBe(200);
  expect(response.headers.get('etag')).toBeTruthy();
  expect(await response.text()).not.toContain('specs');
  expect(findUnique.mock.calls[0][0].select.generations.select.engines.select).not.toHaveProperty('specs');
  findUnique.mockResolvedValueOnce(null);
  expect((await fetch(`${base}/models/${randomUUID()}/options`)).status).toBe(404);
});
