export const ROLES = {
  SUPER_ADMIN: "SuperAdmin",
  ADMIN: "Admin",
  GENERAL_STORE_MANAGER: "GeneralStoreManager",
  BRANCH_STORE_MANAGER: "BranchStoreManager",
  WORKSHOP_MANAGER: "WorkshopManager",
  ACCOUNTANT: "Accountant",
  SERVICE_ADVISOR: "ServiceAdviser",
  TECHNICIAN: "Technician",
  RECEPTIONIST: "Receptionist",
  RECEPTION_MANAGER: "ReceptionManager",
} as const;

export type RoleType = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // ── Dashboard ───────────────────────────────────────────────────────────────
  DASHBOARD_READ: "dashboard:read",

  // ── Notifications ───────────────────────────────────────────────────────────
  NOTIFICATION_READ: "notification:read",
  NOTIFICATION_UPDATE: "notification:update",

  // ── Global Search ───────────────────────────────────────────────────────────
  SEARCH_READ: "search:read",

  // ── Administration — Users ─────────────────────────────────────────────────
  USER_READ: "user:read",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",

  // ── Administration — Roles ────────────────────────────────────────────────
  ROLE_READ: "role:read",
  ROLE_CREATE: "role:create",
  ROLE_UPDATE: "role:update",
  ROLE_DELETE: "role:delete",
  ROLE_PERMISSION_UPDATE: "role:permission:update",

  // ── Branch Management ─────────────────────────────────────────────────────
  BRANCH_READ: "branch:read",
  BRANCH_CREATE: "branch:create",
  BRANCH_UPDATE: "branch:update",
  BRANCH_DELETE: "branch:delete",

  // ── Customer Management ───────────────────────────────────────────────────
  CUSTOMER_READ: "customer:read",
  CUSTOMER_CREATE: "customer:create",
  CUSTOMER_UPDATE: "customer:update",
  CUSTOMER_DELETE: "customer:delete",
  CUSTOMER_DOCUMENT_CREATE: "customer:document:create",
  CUSTOMER_HISTORY_CREATE: "customer:history:create",
  CUSTOMER_ACCOUNT_MANAGE: "customer:account:manage",

  // ── Vehicle Management ────────────────────────────────────────────────────
  VEHICLE_READ: "vehicle:read",
  VEHICLE_CREATE: "vehicle:create",
  VEHICLE_UPDATE: "vehicle:update",
  VEHICLE_DELETE: "vehicle:delete",
  VEHICLE_IMAGE_CREATE: "vehicle:image:create",
  VEHICLE_OWNERSHIP_CREATE: "vehicle:ownership:create",

  // ── Service — Appointments ────────────────────────────────────────────────
  APPOINTMENT_READ: "appointment:read",
  APPOINTMENT_CREATE: "appointment:create",
  APPOINTMENT_UPDATE: "appointment:update",
  APPOINTMENT_DELETE: "appointment:delete",

  // ── Enquiries — Appointment Inquiries ─────────────────────────────────────
  ENQUIRY_READ: "enquiry:read",
  ENQUIRY_CREATE: "enquiry:create",
  ENQUIRY_UPDATE: "enquiry:update",
  ENQUIRY_DELETE: "enquiry:delete",

  // ── Service — Job Cards ───────────────────────────────────────────────────
  JOBCARD_READ: "jobcard:read",
  JOBCARD_CREATE: "jobcard:create",
  JOBCARD_UPDATE: "jobcard:update",

  // ── Service — Inspections ─────────────────────────────────────────────────
  INSPECTION_READ: "inspection:read",
  INSPECTION_CREATE: "inspection:create",

  // ── Service — Estimates ───────────────────────────────────────────────────
  ESTIMATE_READ: "estimate:read",
  ESTIMATE_CREATE: "estimate:create",
  ESTIMATE_APPROVE: "estimate:approve",

  // ── Services Catalog ──────────────────────────────────────────────────────
  SERVICES_READ: "services:read",
  SERVICES_CREATE: "services:create",
  SERVICES_UPDATE: "services:update",
  SERVICES_DELETE: "services:delete",

  // ── Workshop — Assignments ────────────────────────────────────────────────
  ASSIGNMENT_CREATE: "assignment:create",

  // ── Workshop — Job Progress ───────────────────────────────────────────────
  JOBPROGRESS_UPDATE: "jobprogress:update",

  // ── Workshop — Quality Control ────────────────────────────────────────────
  QCSTATUS_UPDATE: "qcstatus:update",

  // ── Workshop — Read ───────────────────────────────────────────────────────
  WORKSHOP_READ: "workshop:read",

  // ── Inventory — Spare Parts ───────────────────────────────────────────────
  SPAREPART_READ: "sparepart:read",
  SPAREPART_CREATE: "sparepart:create",
  SPAREPART_UPDATE: "sparepart:update",
  SPAREPART_DELETE: "sparepart:delete",

  // ── Inventory — Stock ─────────────────────────────────────────────────────
  STOCK_READ: "stock:read",
  STOCK_UPDATE: "stock:update",

  // ── Inventory — Purchase Requests ─────────────────────────────────────────
  PURCHASEREQUEST_READ: "purchaserequest:read",
  PURCHASEREQUEST_CREATE: "purchaserequest:create",
  PURCHASEREQUEST_UPDATE: "purchaserequest:update",

  // ── Inventory — Part Issuances ────────────────────────────────────────────
  PARTISSUANCE_READ: "partissuance:read",
  PARTISSUANCE_CREATE: "partissuance:create",

  // ── Inventory — Part Returns ──────────────────────────────────────────────
  PARTRETURN_READ: "partreturn:read",
  PARTRETURN_CREATE: "partreturn:create",

  // ── Inventory — Transfers ─────────────────────────────────────────────────
  TRANSFER_READ: "transfer:read",
  TRANSFER_CREATE: "transfer:create",
  TRANSFER_UPDATE: "transfer:update",
  TRANSFER_APPROVE: "transfer:approve",
  TRANSFER_REJECT: "transfer:reject",
  TRANSFER_CANCEL: "transfer:cancel",
  TRANSFER_DISPATCH: "transfer:dispatch",
  TRANSFER_RECEIVE: "transfer:receive",

  // ── Finance — Invoices ────────────────────────────────────────────────────
  INVOICE_READ: "invoice:read",
  INVOICE_CREATE: "invoice:create",
  INVOICE_UPDATE: "invoice:update",
  INVOICE_DELETE: "invoice:delete",

  // ── Finance — Payments ────────────────────────────────────────────────────
  PAYMENT_READ: "payment:read",
  PAYMENT_CREATE: "payment:create",

  // ── Finance — Receipts ────────────────────────────────────────────────────
  RECEIPT_READ: "receipt:read",
  RECEIPT_CREATE: "receipt:create",

  // ── Finance — Reports ─────────────────────────────────────────────────────
  FINANCE_REPORT_READ: "financereport:read",

  // ── Credit ────────────────────────────────────────────────────────────────
  CREDIT_APPLICATION_CREATE: "credit:application:create",
  CREDIT_ADJUST: "credit:adjust",

  // ── Audit ─────────────────────────────────────────────────────────────────
  AUDIT_READ: "audit:read",
} as const;

export type PermissionType = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Mapping roles to their default initial permissions for seeding
export const ROLE_PERMISSIONS: Record<RoleType, PermissionType[]> = {
  // Full access
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  // Branch/user/system admin
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DOCUMENT_CREATE,
    PERMISSIONS.CUSTOMER_HISTORY_CREATE,
    PERMISSIONS.CUSTOMER_ACCOUNT_MANAGE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_IMAGE_CREATE,
    PERMISSIONS.VEHICLE_OWNERSHIP_CREATE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.ENQUIRY_READ,
    PERMISSIONS.ENQUIRY_CREATE,
    PERMISSIONS.ENQUIRY_UPDATE,
    PERMISSIONS.ENQUIRY_DELETE,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.JOBCARD_CREATE,
    PERMISSIONS.JOBCARD_UPDATE,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.ESTIMATE_READ,
    PERMISSIONS.ESTIMATE_CREATE,
    PERMISSIONS.ESTIMATE_APPROVE,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.JOBPROGRESS_UPDATE,
    PERMISSIONS.QCSTATUS_UPDATE,
    PERMISSIONS.SPAREPART_READ,
    PERMISSIONS.SPAREPART_CREATE,
    PERMISSIONS.SPAREPART_UPDATE,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.STOCK_UPDATE,
    PERMISSIONS.PURCHASEREQUEST_READ,
    PERMISSIONS.PURCHASEREQUEST_CREATE,
    PERMISSIONS.PURCHASEREQUEST_UPDATE,
    PERMISSIONS.PARTISSUANCE_READ,
    PERMISSIONS.PARTISSUANCE_CREATE,
    PERMISSIONS.PARTRETURN_READ,
    PERMISSIONS.PARTRETURN_CREATE,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.TRANSFER_CREATE,
    PERMISSIONS.TRANSFER_UPDATE,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.TRANSFER_DISPATCH,
    PERMISSIONS.TRANSFER_RECEIVE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.RECEIPT_READ,
    PERMISSIONS.RECEIPT_CREATE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_CREATE,
    PERMISSIONS.SERVICES_UPDATE,
    PERMISSIONS.AUDIT_READ,
  ],

  // Cross-branch inventory manager: manages stock across ALL branches
  [ROLES.GENERAL_STORE_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.SPAREPART_READ,
    PERMISSIONS.SPAREPART_CREATE,
    PERMISSIONS.SPAREPART_UPDATE,
    PERMISSIONS.SPAREPART_DELETE,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.STOCK_UPDATE,
    PERMISSIONS.PURCHASEREQUEST_READ,
    PERMISSIONS.PURCHASEREQUEST_CREATE,
    PERMISSIONS.PURCHASEREQUEST_UPDATE,
    PERMISSIONS.PARTISSUANCE_READ,
    PERMISSIONS.PARTISSUANCE_CREATE,
    PERMISSIONS.PARTRETURN_READ,
    PERMISSIONS.PARTRETURN_CREATE,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.TRANSFER_CREATE,
    PERMISSIONS.TRANSFER_UPDATE,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.TRANSFER_DISPATCH,
    PERMISSIONS.TRANSFER_RECEIVE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.CUSTOMER_READ,
  ],

  // Branch-scoped inventory manager: manages stock for their assigned branch only
  [ROLES.BRANCH_STORE_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.SPAREPART_READ,
    PERMISSIONS.SPAREPART_CREATE,
    PERMISSIONS.SPAREPART_UPDATE,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.STOCK_UPDATE,
    PERMISSIONS.PURCHASEREQUEST_READ,
    PERMISSIONS.PURCHASEREQUEST_CREATE,
    PERMISSIONS.PARTISSUANCE_READ,
    PERMISSIONS.PARTISSUANCE_CREATE,
    PERMISSIONS.PARTRETURN_READ,
    PERMISSIONS.PARTRETURN_CREATE,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.TRANSFER_CREATE,
    PERMISSIONS.TRANSFER_RECEIVE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.CUSTOMER_READ,
  ],

  // Oversees workshop floor: job cards, technician assignments, QC, inventory
  [ROLES.WORKSHOP_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.JOBCARD_CREATE,
    PERMISSIONS.JOBCARD_UPDATE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_DELETE,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.ESTIMATE_READ,
    PERMISSIONS.ESTIMATE_CREATE,
    PERMISSIONS.ESTIMATE_APPROVE,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.JOBPROGRESS_UPDATE,
    PERMISSIONS.QCSTATUS_UPDATE,
    PERMISSIONS.SPAREPART_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_CREATE,
    PERMISSIONS.SERVICES_UPDATE,
    PERMISSIONS.SERVICES_DELETE,
  ],

  // Oversees accounting: finance, invoices, payments, receipts
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.RECEIPT_READ,
    PERMISSIONS.RECEIPT_CREATE,
    PERMISSIONS.FINANCE_REPORT_READ,
  ],

  // Handles estimates, approvals, customer liaison during service
  [ROLES.SERVICE_ADVISOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DOCUMENT_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.JOBCARD_CREATE,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.ESTIMATE_READ,
    PERMISSIONS.ESTIMATE_CREATE,
    PERMISSIONS.ESTIMATE_APPROVE,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.SPAREPART_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.SERVICES_READ,
  ],

  // Executes repairs, updates job card progress
  [ROLES.TECHNICIAN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.JOBCARD_UPDATE,
    PERMISSIONS.INSPECTION_READ,
    PERMISSIONS.INSPECTION_CREATE,
    PERMISSIONS.ESTIMATE_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.WORKSHOP_READ,
    PERMISSIONS.JOBPROGRESS_UPDATE,
    PERMISSIONS.SPAREPART_READ,
  ],

  // Front-desk: registers customers, books appointments, manages vehicles
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_DOCUMENT_CREATE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.ENQUIRY_READ,
    PERMISSIONS.ENQUIRY_CREATE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.INVOICE_READ,
  ],

  // Manages receptionists across all branches; full CRUD on customers, vehicles, appointments
  [ROLES.RECEPTION_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.SEARCH_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.CUSTOMER_DOCUMENT_CREATE,
    PERMISSIONS.CUSTOMER_HISTORY_CREATE,
    PERMISSIONS.CUSTOMER_ACCOUNT_MANAGE,
    PERMISSIONS.VEHICLE_READ,
    PERMISSIONS.VEHICLE_CREATE,
    PERMISSIONS.VEHICLE_UPDATE,
    PERMISSIONS.VEHICLE_DELETE,
    PERMISSIONS.VEHICLE_IMAGE_CREATE,
    PERMISSIONS.VEHICLE_OWNERSHIP_CREATE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_DELETE,
    PERMISSIONS.ENQUIRY_READ,
    PERMISSIONS.ENQUIRY_CREATE,
    PERMISSIONS.ENQUIRY_UPDATE,
    PERMISSIONS.ENQUIRY_DELETE,
    PERMISSIONS.JOBCARD_READ,
    PERMISSIONS.JOBCARD_CREATE,
    PERMISSIONS.SERVICES_READ,
  ],
};
