
"use client";
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Download,Printer } from 'lucide-react';
import { PageHeader } from '@/components/headers/page-header';
import { Field,inputCls } from '@/components/forms/FormField';
import { Button } from '@/components/ui/button';
import { WorkshopPicker } from '@/features/job-cards/components/WorkshopPicker';
import { useBranchStore } from '@/store/branch.store';
import { useAuth } from '@/features/auth/hooks/use-auth';
import { getPartyReport,getReportSettings,exportPartyReport,printPartyReport,type ReportKind,type ReportFilters,type ReportRow } from '../api/party-report.api';
import { FinanceReportNav,PARTY_REPORTS } from './finance-report-nav';
export const VENDOR_PARTIES_ENABLED=false;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'});
function columns(kind:ReportKind,limits:number[]){const base=[['code','Code'],['name','Party']];
 if(kind==='ledger')return [...base,['date','Date'],['number','Document'],['kind','Type'],['narration','Narration'],['debit','Debit'],['credit','Credit'],['runningBalance','Balance']];
 if(kind==='bill')return [...base,['side','Side'],['date','Date'],['number','Document'],['amount','Amount'],['adjusted','Adjusted'],['balance','Outstanding / credit'],['age','Days old']];
 if(kind==='age')return [...base,...limits.map((n,i)=>['bucket'+i,(i?limits[i-1]+1:0)+'–'+n+' days']),['bucket5','Over '+limits[4]],['debits','Debits'],['credits','Credits'],['net','Net']];
 return [...base,['debits','Debits'],['credits','Credits'],['net','Net']];
}
export function PartyReportsPage({kind}:{kind:ReportKind}){
 const {user,hasPermission}=useAuth();const branches=useBranchStore(s=>s.branches);const active=useBranchStore(s=>s.activeBranch?.id);const params=useSearchParams();const customerId=params.get('customerId')||undefined;
 const admin=user?.role==='Admin'||user?.role==='SuperAdmin';const permission=PARTY_REPORTS.find(r=>r.kind===kind)!.permission;
 const settings=useQuery({queryKey:['party-report-settings'],queryFn:getReportSettings,enabled:hasPermission(permission),staleTime:60000});
 const initial:ReportFilters={kind,customerId,branchId:admin?(params.get('branchId')||active):active,order:'name',partyStatus:'ALL',from:today().slice(0,4)+'-01-01',to:today(),asOn:today(),showCredit:'false',page:1,pageSize:25};
 const [filters,setFilters]=useState(initial);const [applied,setApplied]=useState<ReportFilters>();const [ages,setAges]=useState<string>();const [validation,setValidation]=useState('');const [busy,setBusy]=useState<'export'|'print'>();
 const effectiveFilters={...filters,branchId:admin?filters.branchId:active};const defaults=settings.data?.ageLimits??[30,60,90,120,180];const ageText=ages??defaults.join(',');const ageValues=ageText.split(',').map(Number);const validAges=ageValues.length===5&&ageValues.every((n,i)=>Number.isInteger(n)&&n>0&&n<=3650&&(i===0||n>ageValues[i-1]));
 const validBranch=admin||!!active;const scopedApplied=applied&&(admin||applied.branchId===active)?applied:undefined;
 const report=useQuery({queryKey:['party-report',scopedApplied],queryFn:({signal})=>getPartyReport(scopedApplied!,signal),enabled:!!scopedApplied&&hasPermission(permission),staleTime:30000});
 function change<K extends keyof ReportFilters>(key:K,value:ReportFilters[K]){setFilters(f=>({...f,[key]:value,page:1}));}
 function submit(event:React.FormEvent){event.preventDefault();if(!validBranch){setValidation('Select your assigned branch.');return;}if(kind==='ledger'&&(!filters.from||!filters.to||filters.from>filters.to)){setValidation('Choose a valid ledger date range.');return;}if(kind!=='ledger'&&!filters.asOn){setValidation('Choose an as-on date.');return;}if(kind==='age'&&!validAges){setValidation('Enter five increasing whole-day limits from 1 to 3650.');return;}setValidation('');setApplied({...effectiveFilters,ageLimits:kind==='age'?ageText:undefined,page:1});}
 async function output(action:'export'|'print'){if(!scopedApplied)return;const target=action==='print'?window.open('','_blank'):null;if(action==='print'&&!target){toast.error('Allow popups to print this report.');return;}setBusy(action);try{if(target){target.document.body.textContent='Preparing report…';await printPartyReport(scopedApplied,target);}else await exportPartyReport(scopedApplied);toast.success(action==='print'?'Report ready to print':'Excel workbook downloaded');}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))toast.error(e instanceof Error?e.message:'Report could not be prepared');}finally{setBusy(undefined);}}
 const data=report.data;const rows=data?.rows??[];const cols=columns(kind,data?.ageLimits??defaults);const changed=scopedApplied&&JSON.stringify({...effectiveFilters,ageLimits:kind==='age'?ageText:undefined,page:scopedApplied.page})!==JSON.stringify(scopedApplied);
 return <div className="flex flex-col gap-5 p-4 lg:p-6"><FinanceReportNav/><PageHeader title={PARTY_REPORTS.find(r=>r.kind===kind)!.title} description="Dated financial documents and adjustments, in NGN. Calendar dates use Africa/Lagos." actions={<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!rows.length||!!busy||report.isFetching||!!changed} onClick={()=>output('print')}><Printer className="size-4"/>{busy==='print'?'Preparing…':'Print all results'}</Button><Button size="sm" variant="outline" disabled={!rows.length||!!busy||report.isFetching||!!changed} onClick={()=>output('export')}><Download className="size-4"/>{busy==='export'?'Exporting…':'Export Excel'}</Button></div>}/>
 <form onSubmit={submit} className="grid gap-4 rounded-xl border bg-background p-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Party report filters">
 {kind==='ledger'?<><Field label="From date"><input type="date" required max={today()} className={inputCls} value={filters.from} onChange={e=>change('from',e.target.value)}/></Field><Field label="To date"><input type="date" required min={filters.from} max={today()} className={inputCls} value={filters.to} onChange={e=>change('to',e.target.value)}/></Field></>:<Field label="As on date"><input type="date" required max={today()} className={inputCls} value={filters.asOn} onChange={e=>change('asOn',e.target.value)}/></Field>}
 <Field label="Accounts"><select className={inputCls} value="DEBTORS" onChange={()=>{}}><option value="DEBTORS">Sundry debtors</option>{VENDOR_PARTIES_ENABLED&&<option value="CREDITORS">Sundry creditors</option>}</select></Field>
 <Field label="Party status"><select className={inputCls} value={filters.partyStatus} onChange={e=>change('partyStatus',e.target.value as ReportFilters['partyStatus'])}><option value="ALL">All parties</option><option value="CUSTOMER">Customers</option><option value="DEALER">Dealers</option><option value="FA_PARTY">FA parties</option></select></Field>
 <Field label="Order"><select className={inputCls} value={filters.order} onChange={e=>{change('order',e.target.value as 'name'|'code');change('fromCustomerId',undefined);change('toCustomerId',undefined);}}><option value="name">Name-wise</option><option value="code">Code-wise</option></select></Field>
 <Field label="Branch"><select className={inputCls} value={effectiveFilters.branchId??''} disabled={!admin} onChange={e=>{change('branchId',e.target.value||undefined);change('fromCustomerId',undefined);change('toCustomerId',undefined);}}>{admin&&<option value="">All branches</option>}{!admin&&!active&&<option value="">Select a branch in the header</option>}{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></Field>
 {filters.customerId?<div className="flex items-end gap-2 text-sm"><p>Filtered to this customer’s account.</p><Button type="button" variant="outline" size="sm" onClick={()=>change('customerId',undefined)}>Show all parties</Button></div>:null}
 {!filters.customerId&&(['fromCustomerId','toCustomerId'] as const).map((key,i)=><WorkshopPicker key={key+effectiveFilters.branchId+filters.order} label={i?'To party':'From party'} endpoint={'/finance/party-reports/parties?kind='+kind+'&order='+filters.order+(effectiveFilters.branchId?'&branchId='+effectiveFilters.branchId:'')} collection="customers" value={filters[key]} onChange={id=>change(key,id||undefined)} disabled={!validBranch} formatLabel={r=>[r.code,r.name].filter(Boolean).join(' · ')}/>)}
 {kind==='age'&&<fieldset className="grid gap-2 sm:col-span-2 lg:col-span-4"><legend className="mb-2 text-sm font-medium">Age limits (days)</legend><div className="grid grid-cols-5 gap-2">{Array.from({length:5},(_,i)=><input key={i} aria-label={'Age limit '+(i+1)} aria-invalid={!validAges} type="number" min="1" max="3650" step="1" className={inputCls} value={ageText.split(',')[i]??''} onChange={e=>{const parts=ageText.split(',');parts[i]=e.target.value;setAges(parts.join(','));}}/>)}</div>{!validAges&&<p role="alert" className="text-sm text-destructive">Enter five increasing whole-day limits.</p>}</fieldset>}
 {(kind==='age'||kind==='bill')&&<label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={filters.showCredit==='true'} onChange={e=>change('showCredit',e.target.checked?'true':'false')}/>Show customers with a credit balance</label>}
 <div className="flex flex-wrap items-center gap-3 sm:col-span-2 lg:col-span-4"><Button disabled={!validBranch||report.isFetching||(kind==='age'&&!validAges)}>{report.isFetching?'Loading…':'Run report'}</Button>{changed&&<p role="status" className="text-sm text-muted-foreground">Filters changed. Run the report to update results.</p>}{validation&&<p role="alert" className="text-sm text-destructive">{validation}</p>}</div>
 </form>
 {!scopedApplied?<p className="py-12 text-center text-sm text-muted-foreground">Choose filters and run the report.</p>:report.isLoading?<div className="h-40 animate-pulse rounded-xl bg-muted" aria-busy="true" aria-label="Loading report"/>:report.isError?<div role="alert"><p className="text-destructive">Report could not be loaded. Check your filters and branch access.</p><Button variant="outline" className="mt-3" onClick={()=>report.refetch()}>Retry</Button></div>:!rows.length?<p className="py-12 text-center text-sm text-muted-foreground">No records match these filters.</p>:<>
 <div className="flex flex-wrap gap-4 rounded-lg bg-background p-4 text-sm" aria-live="polite">{Object.entries(data?.totals??{}).filter(([k,v])=>k!=='total'&&typeof v==='number').map(([k,v])=><span key={k}>{cols.find(([key])=>key===k)?.[1]??k}: <strong>{money.format(v as number)}</strong></span>)}<span>{data?.meta.total} rows · totals cover all results</span></div>
 <div className="overflow-x-auto rounded-xl border bg-background"><table className="w-full text-sm"><caption className="sr-only">{PARTY_REPORTS.find(r=>r.kind===kind)!.title} · report results</caption><thead className="border-b bg-muted/40"><tr>{cols.map(([k,label])=><th key={k} scope="col" className="whitespace-nowrap px-3 py-3 text-left font-medium">{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><ReportTableRow key={String(row.id??row.customerId)} row={row} previous={rows[index-1]} last={rows[index+1]?.customerId!==row.customerId} cols={cols} kind={kind}/>)}</tbody></table></div>
 <div className="flex items-center justify-between gap-3"><Button variant="outline" disabled={scopedApplied.page===1||report.isFetching} onClick={()=>setApplied({...scopedApplied,page:scopedApplied.page-1})}>Previous</Button><span className="text-sm">Page {data?.meta.page} of {data?.meta.totalPages}</span><Button variant="outline" disabled={scopedApplied.page>=data!.meta.totalPages||report.isFetching} onClick={()=>setApplied({...scopedApplied,page:scopedApplied.page+1})}>Next</Button></div>
 </>}
 </div>;
}
function ReportTableRow({row,previous,last,cols,kind}:{row:ReportRow;previous?:ReportRow;last:boolean;cols:string[][];kind:ReportKind}){
 const grouped=kind==='ledger'||kind==='bill';return <>{grouped&&row.customerId!==previous?.customerId&&<tr className="border-b bg-muted/30"><th colSpan={cols.length} scope="rowgroup" className="px-3 py-3 text-left">{row.code} · {row.name}{kind==='ledger'&&<span className="ml-4 font-normal">Opening {money.format(Number(row.opening))}</span>}</th></tr>}<tr className="border-b last:border-0 hover:bg-muted/20">{cols.map(([k])=><td key={k} className={'px-3 py-3 '+(typeof row[k]==='number'?'text-right tabular-nums':'')}>{k==='date'&&row[k]?new Intl.DateTimeFormat('en-NG',{timeZone:'Africa/Lagos'}).format(new Date(String(row[k]))):typeof row[k]==='number'?k==='age'?row[k]:money.format(row[k] as number):row[k]}</td>)}</tr>{grouped&&last&&<tr className="border-b bg-muted/20"><td colSpan={cols.length} className="px-3 py-2 text-right font-semibold">{kind==='ledger'?'Closing balance':'Party net'} {money.format(Number(kind==='ledger'?row.closing:row.net))}</td></tr>}</>;
}
